### ISSUE TITLE
Unclear how much work I need to do

### ISSUE THREAD

**Issue by Trevoke** [wunderflats/popman#1]
Hi,

The example made me think that the module would magically connect the provided source div with a click handler to hide and show the popover, but the example code looks like I need to wire it up myself?

**Comment by maximilianschmitt** [comment]
Hi @Trevoke!

Take a look at this very simple example:

```javascript
const Popover = require('popman')

const open = true

<Popover open={open} around={<div>Hello</div>}>
  Hello, i am the popover content
</Popover>
```

This is all you need to show a popover (positioned around the `<div>Hello</div>`). You can hide it by setting `open` to `false`. How you show/hide the popover is completely up to you. You might want to show it on mouse over, on click or whatever.

The source is **not** magically wired up with a click handler. You check out how `tipman` uses `popman` to render tooltips on mouseover: https://github.com/wunderflats/tipman/blob/master/src/index.js

If you need to show popovers on click often, you can easily build a thin little wrapper component around `popman` that wires everything up for you.

Let me know if you have any more questions.

Best,
Max

**Comment by Trevoke** [comment]
Ah, I see. This package is not a popup handler, it simply positions a particular div in position to another div?

**Comment by maximilianschmitt** [comment]
Hey @Trevoke. Yeah, it lets you position popovers for things like dropdown-menus and tooltips.

**Comment by Trevoke** [comment]
Hi,

Thanks for the answer. I ended up just implementing it myself, as it was simpler to wire it all up myself than to include such a minimal component.

Had the package provided actual popup management, I would have been more than happy to use it, but it turned out to not fit my needs.

Thanks for contributing to F/OSS :)

**Comment by maximilianschmitt** [comment]
Great, best of luck to you and thanks for contributing! :)
